pipeline {
  agent{
    docker{
      image 'python:2.7.16-slim'
    }
  }

  stages{
    stage('build'){
      when{
        changeset "**/vote/**"
      }
      steps{
        echo "Compiling Vote App"
        dir('vote'){
          sh 'pip install -r requirements.txt'
        }
      }
    }
    stage('test'){
      when{
        changeset "**/vote/**"
      }
      steps{
        echo "Running Unit Tests on Vote App"
        dir('vote'){
          sh 'nosetests -v'
        }
      }
    }
  }

  post{
    always{
      echo "Pipeline for Worker is complete.."
    }
    failure{
      slackSend (channel: "instavote-cd", message: "Build Failure - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
    success{
      slackSend (channel: "instavote-cd", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
  }
}
