pipeline {
  agent any

  tools{
    maven "3.6.3"
  }

  stages{
    stage('build'){
      steps{
        echo "Compiling Worker App"
        dir('worker'){
          sh 'mvn compile'
        }
      }
    }
    stage('test'){
      steps{
        echo "Running Unit Tests on Worker App"
        dir('worker'){
          sh 'mvn clean test'
        }
      }
    }
    stage('package'){
      steps{
        echo "Packaging Worker App"
        dir('worker'){
          sh 'mvn package -DskipTests'
        }
      }
    }
  }

  post{
    always{
      archoveArtifacts artifacts: '**/target/*.jar', fingerprint: true
      echo "Pipeline for Worker is complete.."
    }
  }
}
